# Generated by Django 5.1.4 on 2025-05-27 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_patient"),
    ]

    operations = [
        migrations.AddField(
            model_name="claim",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.patient",
            ),
        ),
    ]
