# Generated by Django 5.1.4 on 2025-05-27 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_claim_patient"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="external_patient_id",
            field=models.CharField(editable=False, max_length=100, unique=True),
        ),
    ]
